In [3]:
import numpy as np

create array

In [2]:
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [8]:
price[0:]

array([5, 5, 5])

In [9]:
food[1]

'samosa'

In [10]:
price.mean()

5.0

In [11]:
#zerps method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
#ones array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [17]:
#specify 
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
#specify interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
#table
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
#line_space
np.linspace(1,10, num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
#array function
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])

In [31]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [32]:
b=np.array([5,56,65,65656,56,565,])

In [33]:
#2d array

In [36]:
x= np.array([[5,6,4,2,3],[7,8,9,2,2]])
x


array([[5, 6, 4, 2, 3],
       [7, 8, 9, 2, 2]])

In [37]:
y= np.array([[6,5,8,2,4],[4,7,8,4,6]])
y

array([[6, 5, 8, 2, 4],
       [4, 7, 8, 4, 6]])

In [39]:
c=np.concatenate((x,y),axis=0)
c

array([[5, 6, 4, 2, 3],
       [7, 8, 9, 2, 2],
       [6, 5, 8, 2, 4],
       [4, 7, 8, 4, 6]])

In [40]:
c=np.concatenate((x,y),axis=1)
c

array([[5, 6, 4, 2, 3, 6, 5, 8, 2, 4],
       [7, 8, 9, 2, 2, 4, 7, 8, 4, 6]])

In [44]:
c.sort()
c

array([[2, 2, 3, 4, 4, 5, 5, 6, 6, 8],
       [2, 2, 4, 4, 6, 7, 7, 8, 8, 9]])

In [45]:
#find dimensions
c.ndim

2

In [46]:
c.size

20

In [47]:
c.shape

(2, 10)

In [ ]:
#